name: SCA Workflow

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: blackducksoftware/detect:10

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello from SCA image
