name: SCA Workflow

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  package-manager-scan:
    container:
      image: "blackducksoftware/detect:10"
    runs-on: ["sca"]
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello from SCA image
  signature-scan:
    container:
      image: "blackducksoftware/detect:10"
    runs-on: ["sca"]
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello from SCA image
  binary-scan:
    container:
      image: "blackducksoftware/detect:10"
    runs-on: ["sca"]
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello from SCA image
  container-scan:
    container:
      image: "blackducksoftware/detect:10"
    runs-on: ["sca"]
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello from SCA image
